baseURL = ""

languageCode = "en-us"

title = "Arthematics"

enableRobotsTXT = true

[taxonomies]
	tag = "tags"

[permalinks]
	tags = "/portfolio/tag/:slug/"

[params]
	description = "Mathematical beauty"
	images = [".jpg"]
	title = "Arthematics"
