baseURL = ""

languageCode = "en-us"

title = "Castillete"

enableRobotsTXT = true

[taxonomies]
	tag = "tags"

[permalinks]
	tags = "/portfolio/tag/:slug/"

[params]
	description = "El Castillete of Armando Reverón"
	images = ["/jpg/chinita-de-el-playon.jpg"]
	title = "Castillete"
