backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: content/portfolio/images
public_folder: portfolio/images
collections:
  - name: "Portfolio"
    label: "Painting"
    folder: "content/portfolio"
    create: true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Image"
        name: "img"
        widget: "image"
        media_library:
          config:
            multiple: false

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Creation date"
        name: "date"
        widget: "datetime"

      - label: "Tags"
        name: "tags"
        widget: "list"

      - label: "Alt text"
        name: "alt"
        widget: "string"
